### ISSUE TITLE
setCurrentLevel problem

### ISSUE THREAD

**Issue by iSpartak** [simpliflow/SFGaugeView#3] opened 2014-02-13 22:05 UTC
HI, 

in my viewDidLoad I call

self.graphSlider.currentLevel = 0;

As result I have proper setup for the level but there are some filed areas appear on left and right side. If I move the slider they are disappear - check screenshot.

There is also problem with sliding. Sometimes your not able to reach min or max position as slider doesnt allow you to do so and stopped in 3-4 millilitres before the end (left or right) value. 
![problem](https://f.cloud.github.com/assets/1653195/2165587/e7dfd9da-94fa-11e3-9b9d-70d550f3af51.png)

**Comment by iSpartak** [comment] 2014-02-13 22:11
another idea would be to add a protocol for level change and notify listeners. smth like

@protocol SFGaugeDelegate
@required
- (void) levelChanged:(NSInteger) currentLevel;
  @end

notify listeners from (NSInteger) currentLevel implementation.

btw, nice work!

**Comment by tomgong** [comment] 2014-02-14 08:10
I cannot reproduce the described error. Maybe you could provide some more information (how do you initialize the SFGaugeView, what parameter do you set, ...).
- Delegate method for tracking level changes added (see Readme). 
- Minor improvements on gesture recognition (left/right value problem).

**Comment by iSpartak** [comment] 2014-02-15 08:31
```
self.graphSlider.bgColor     = [UIColor colorWithRed:0/255.0 green:124/255.0 blue:205/255.0 alpha:1];
self.graphSlider.needleColor = [UIColor colorWithRed:0/255.0 green:39/255.0 blue:64/255.0 alpha:1];
self.graphSlider.hideLevel   = YES;

self.graphSlider.maxlevel = 115; // initial

self.graphSlider.currentLevel = 0;
```

In my NIB I put small UIView (290x250) and set class to SFGaugeView (no springboard)

**Comment by tomgong** [comment] 2014-02-16 08:45
I see no problem when loading from XIB file. 
I've added an example (class SFViewController; commented block in viewDidLoad) to the test app

**Comment by iSpartak** [comment] 2014-02-16 21:15
ok, that's funny. I've found that problem actually can be reproduced only on the real device. I usually do development with my iPhone and not Simulator. So... On Simulator there is no any problem but there is on real device.  I've made sample project which works fine on Simulator but not on Device. 

http://ispartak.com/Test_Slider.zip

I have iPhone 5 with up to date iOS

**Comment by tomgong** [comment] 2014-02-17 19:21
Issue should be fixed. Please check out Version 0.0.5 
Thx for your support.

**Closed as completed by tomgong** 2014-02-17 19:21 UTC
